
export const FETCH_PARAMS_FROM_URL = 'FETCH_PARAMS_FROM_URL';
export const FETCH_EFORM_TEMPLATE_FROM_SERVER = 'FETCH_EFORM_TEMPLATE_FROM_SERVER';
export const FETCH_USER_ROLE_FROM_SERVER = 'FETCH_USER_ROLE_FROM_SERVER';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const ADD_SECTION = 'ADD_SECTION';
export const REMOVE_SECTION = 'REMOVE_SECTION';
export const DOUBLE_SECTION = 'DOUBLE_SECTION';
export const ADD_ROW = 'ADD_ROW';
export const REMOVE_ROW = 'REMOVE_ROW';
export const ADD_FIELD = 'ADD_FIELD';
export const GET_LIST_TEMPLATE_FROM_SERVER = 'GET_LIST_TEMPLATE_FROM_SERVER';
export const REMOVE_TEMPLATE = 'REMOVE_TEMPLATE';



